name: Upload to S3 - SDB3 - Q3

on:
  pull_request:
    branches: [main, master]
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Zipping files
      run: zip -r ${{ github.event.repository.name }}.zip . -x '*.git*' '*.idea*'

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID_Q3_SDB3 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_Q3_SDB3 }}
        aws-region: ${{ secrets.AWS_REGION_Q3_SDB3 }}

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 cp ${{ github.event.repository.name }}.zip s3://${{ secrets.AWS_BUCKET_Q3_SDB3 }}/${{ secrets.AWS_DIRNAME_Q3_SDB3 }}/${{ github.event.repository.name }}.zip
